import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { openSync } from "fontkit";
import { buildEcosystem } from "./build-ecosystem.mjs";
import { buildProject } from "./build-projects.mjs";

const brandRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const sourceRoot = path.join(brandRoot, "source");
const canvas = "#F7F6F2";
const charcoal = "#272522";

const projects = {
  ecosystem: { name: "Ecosystem", accent: "#3F5F56", accentDark: "#ADC6BA" },
  ink: { name: "Ink", accent: "#7A303B", accentDark: "#E2A3AC" },
  os: { name: "OS", accent: "#485F79", accentDark: "#A9C0D8" },
  conclave: { name: "Conclave", accent: "#65516D", accentDark: "#C9B0D3" },
  courier: { name: "Courier", accent: "#85621D", accentDark: "#E3C477" },
  lyre: { name: "Lyre", accent: "#456348", accentDark: "#AFC9AE" },
  brush: { name: "Brush", accent: "#994D34", accentDark: "#E5AD99" },
  pick: { name: "Pick", accent: "#285E63", accentDark: "#95C6CA" },
  familiar: { name: "Familiar", accent: "#52634A", accentDark: "#BACBAD" },
  herald: { name: "Herald", accent: "#824631", accentDark: "#E4B098" },
  press: { name: "Press", accent: "#4D596D", accentDark: "#BAC6DD" },
  charter: { name: "Charter", accent: "#70582E", accentDark: "#D9C297" },
};

const sha256 = (data) => createHash("sha256").update(data).digest("hex");

async function write(relative, data) {
  const destination = path.join(brandRoot, relative);
  await fs.mkdir(path.dirname(destination), { recursive: true });
  await fs.writeFile(destination, data);
}

async function buildSignature() {
  const vector = await fs.readFile(
    path.join(sourceRoot, "the-wizards.svg"),
    "utf8",
  );
  const raster = await sharp(Buffer.from(vector))
    .resize({ width: 1512 })
    .png()
    .toBuffer();
  await write("signature/the-wizards.svg", vector);
  await write("signature/the-wizards.png", raster);
  await write(
    "signature/the-wizards-reversed.svg",
    vector.replaceAll(charcoal, canvas),
  );
  await write(
    "signature/the-wizards-monochrome.svg",
    vector.replaceAll(charcoal, "#000000"),
  );
  return { vector, raster };
}

const files = {};

function lettering(word, size, face) {
  const run = face.layout(word);
  const scale = size / face.unitsPerEm;
  let advance = 0;
  const paths = run.glyphs.map((glyph, index) => {
    const position = run.positions[index];
    const shape =
      '<path transform="translate(' +
      ((advance + position.xOffset) * scale).toFixed(3) +
      " " +
      (-position.yOffset * scale).toFixed(3) +
      ") scale(" +
      scale +
      " " +
      -scale +
      ')" d="' +
      glyph.path.toSVG() +
      '"/>';
    advance += position.xAdvance;
    return shape;
  });
  return { body: paths.join(""), width: advance * scale };
}

async function emit(relative, data, extra = {}) {
  await write(relative, data);
  const buffer = Buffer.from(data);
  const raster = relative.endsWith(".ico")
    ? buffer.subarray(buffer.readUInt32LE(18))
    : buffer;
  const metadata = await sharp(raster).metadata();
  files[relative] = {
    sha256: sha256(data),
    width: metadata.width,
    height: metadata.height,
    bytes: Buffer.byteLength(data),
    ...extra,
  };
}

const signature = await buildSignature();
const layouts = JSON.parse(
  await fs.readFile(path.join(sourceRoot, "project-layouts.json"), "utf8"),
);
for (const [id, project] of Object.entries(projects)) {
  if (id === "ecosystem") await buildEcosystem(brandRoot, emit);
  else {
    const caption =
      id === "ink"
        ? lettering(
            "Wizzy / experimental / pre-0.1 / source-only",
            24,
            openSync(
              path.join(
                brandRoot,
                "fonts/instrument-sans-latin-wght-normal.woff2",
              ),
            ),
          )
        : null;
    await buildProject(
      brandRoot,
      id,
      project,
      signature.vector,
      layouts[id],
      emit,
      caption,
    );
  }
}

const tokens = JSON.parse(
  await fs.readFile(path.join(brandRoot, "tokens.json"), "utf8"),
);
tokens.version = 5;
tokens.projects = Object.fromEntries(
  Object.entries(projects).map(([id, p]) => [
    id,
    { light: p.accent, dark: p.accentDark },
  ]),
);
await write("tokens.json", JSON.stringify(tokens, null, 2) + "\n");
const cssRole = (name) => name.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());
const palette = (mode) =>
  Object.entries(tokens[mode])
    .map(([name, value]) => "  --wz-" + cssRole(name) + ": " + value + ";")
    .join("\n");
let css =
  "/* Generated by tooling/build-assets.mjs. */\n:root {\n  color-scheme: light;\n" +
  palette("light") +
  '\n  --wz-font-display: "Newsreader", Georgia, serif;\n  --wz-font-interface: "Instrument Sans", system-ui, sans-serif;\n  --wz-font-mono: ui-monospace, "Cascadia Code", "SFMono-Regular", Consolas, monospace;\n  --wz-radius-small: .35rem;\n  --wz-radius-medium: .7rem;\n  --wz-shadow-raised: 0 18px 48px rgb(39 37 34 / .12);\n  --wz-accent: var(--wz-accent-light);\n}\n';
for (const [id, p] of Object.entries(projects))
  css +=
    (id === "ecosystem" ? ":root,\n" : "") +
    ':root[data-project="' +
    id +
    '"] {\n  --wz-accent-light: ' +
    p.accent +
    ";\n  --wz-accent-on-dark: " +
    p.accentDark +
    ";\n}\n";
const darkCss =
  "  color-scheme: dark;\n" +
  palette("dark") +
  "\n  --wz-accent: var(--wz-accent-on-dark);\n  --wz-shadow-raised: 0 20px 54px rgb(0 0 0 / .34);\n";
css +=
  ':root[data-theme="dark"] {\n' +
  darkCss +
  '}\n@media (prefers-color-scheme: dark) {\n:root:not([data-theme="light"]) {\n' +
  darkCss +
  "}\n}\n";
await write("tokens.css", css);
await write(
  "manifest.json",
  JSON.stringify(
    {
      version: 5,
      direction:
        "Calligraphy and watercolor: approved original signature, drawn project lettering, and instrument marks",
      signature: { sha256: sha256(signature.vector) },
      projects,
      files,
    },
    null,
    2,
  ) + "\n",
);
console.log(
  "Built brand package v5: " +
    Object.keys(projects).length +
    " families, " +
    Object.keys(files).length +
    " exports.",
);
